server:
  port: 0
  servlet:
    context-path: /client-person

logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  config:
    import:
      optional:configserver:
  devtools:
    restart:
      enabled: true
  application:
    name: client-person
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/nttdata_db
    username: postgres
    password: postgres
    schema: client_person
    hikari:
      pool-name: Hikari
      connection-timeout: 20000 # Maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 # Minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 # Maximum pool size
      idle-timeout: 10000 # Maximum idle time for connection
      max-lifetime: 1000 # Maximum lifetime in milliseconds of a connection in the pool after it is closed
      auto-commit: true
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        hbm2dll:
          create_namespaces: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: group_client_person
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /actuator