spring:
  application:
    name: discover-server

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
    #prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false