spring:
  application:
    name: discover-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false