spring:
  application:
    name: discover-server

server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false